print("Ingrese un nombre")
nombre = input()
print(nombre + " ha comenzado hoy su primer curso de Generation")
print("Ingrese puesto")
puesto = input()
print("Se están formando como " + puesto + ".")
print("Ingrese un adjetivo")
adjetivo1 = input()
print("Ingrese otro adjetivo")
adjetivo2 = input()
print ("Su compañero les pareció muy " + adjetivo1 + " pero su profesor era, cuando menos, " + adjetivo2 + ".")
print("Ingrese una comida")
comida1 = input()
print("Ingrese otra comida")
comida2 = input()
print("Para comer, comen " + comida1 + " y " + comida2 + " mientras repasan sus notas")
print("Ingrese un sentimiento")
sentimiento = input()
print("Sienten " + sentimiento + " pero están decididos a completar el curso")